# Generated by Django 5.0.5 on 2024-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[("B", "Bueno"), ("R", "Regular"), ("M", "Malo")],
                        max_length=1,
                    ),
                ),
                ("observaciones", models.TextField(max_length=1000)),
                ("ultimaActividad", models.TextField(max_length=200)),
                ("ubicacion", models.TextField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
